#!/bin/sh
xrdb ~/.local/share/xresources/tomorrow-night &
xset r rate 300 50 &
slstatus &
xbanish &
pidof dunst || dunst &
xsetroot -cursor_name left_ptr &
setxkbmap -layout us -option ctrl:nocaps &
#xsetroot -solid "#1d2021" &
xwallpaper --zoom ~/ext/Media/Pix/wallpapers/gondola.png &
pidof mpd || mpd &
redshift &
jackd -d alsa &
pulseaudio -D &
