#!/bin/sh
xrdb ~/.local/share/xresources/nord &
xset r rate 300 50 &
slstatus &
xbanish &
pidof dunst || dunst &
xsetroot -cursor_name left_ptr &
setxkbmap -layout us -option ctrl:nocaps &
pidof jackd || jackd -d alsa &
pidof pulseaudio || pulseaudio -D &
#xsetroot -solid "#1d2021" &
xwallpaper --stretch ~/ext/Media/Pix/wallpapers/nord-arctic-fox.png &
pidof mpd || mpd &
redshift &
